spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/loyw
    username: sa
    password: 1
    driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

cloud:
  aws:
    credentials:
      profile-name: loyw-spring
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: loyw
    sqs:
      queue: https://sqs.us-east-2.amazonaws.com/587356586656/loyw.fifo

server:
  tomcat:
    max-http-form-post-size: 5MB
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
    com.amazonaws.util:
      EC2MetadataUtils: error